# Generated by Django 4.1.7 on 2023-03-14 23:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producttracking",
            name="tracking_interval",
            field=models.IntegerField(
                choices=[(1, "One Hour"), (12, "Twelve Hours"), (24, "One Day")],
                default=12,
            ),
        ),
    ]
