services:
  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    entrypoint: [ "./docker-entrypoint.sh" ]
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASS}
      - POSTGRES_DB=${DATABASE_NAME}

  rabbitmq:
    image: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  celery-worker:
    restart: always
    build:
      context: .
    depends_on:
      - rabbitmq
    command: celery -A src worker -l info
    env_file:
      - .env

  celery-beat:
    restart: always
    build:
      context: .
    command: celery -A src beat -l info
    env_file:
      - .env

  flower:
    image: mher/flower
    ports:
      - "5555:5555"
    volumes:
      - ./wait-for-it.sh:/wait-for-it.sh
    command: sh -c "chmod a+x /wait-for-it.sh && /wait-for-it.sh"
